name: "Setup Godot CI/CD"
description: "Setup Godot (with or without .NET) on macOS, Linux CI/CD runners."
author: "Niranjan Shk"
branding:
  icon: "play"
  color: "blue"

inputs:
  version:
    description: "Godot version (e.g. 4.2.1)"
    required: true
  headless:
    description: "Install headless version (Linux only). Ignored on macOS."
    required: false
    default: "true"
  dotnet:
    description: "Install the .NET / mono version (adds C# support). Also selects the matching mono export-template archive when install-export-templates is true."
    required: false
    default: "false"
  install-export-templates:
    description: "Download and install export templates into the standard Godot templates directory."
    required: false
    default: "false"
  cache-strategy:
    description: "Caching strategy: 'github' (uses actions/cache, default for cloud runners), 'local' (filesystem cache, recommended for self-hosted runners), or 'none' (no caching)"
    required: false
    default: "github"
  local-cache-dir:
    description: "Local cache directory for downloaded files (only used when cache-strategy is 'local'). Defaults to /tmp/godot-cache"
    required: false
    default: "/tmp/godot-cache"

outputs:
  godot-path:
    description: Absolute path to the installed godot binary.
    value: ${{ steps.set-var.outputs.godot-path }}
  templates-path:
    description: Absolute path to the export-templates directory (empty string when install-export-templates is false).
    value: ${{ steps.set-var.outputs.templates-path }}

runs:
  using: "composite"
  steps:
    - name: Set variables
      id: set-var
      shell: bash
      env:
        INPUT_VERSION:   ${{ inputs.version }}
        INPUT_HEADLESS:  ${{ inputs.headless }}
        INPUT_DOTNET:    ${{ inputs.dotnet }}
        INPUT_TEMPLATES: ${{ inputs.install-export-templates }}
        INPUT_CACHE_STRATEGY: ${{ inputs.cache-strategy }}
        INPUT_LOCAL_CACHE_DIR: ${{ inputs.local-cache-dir }}
        RUNNER_OS:       ${{ runner.os }}
      run: |
        set -euo pipefail

        VERSION="${INPUT_VERSION}"
        TAG="${VERSION}-stable"
        GH_BASE="https://github.com/godotengine/godot/releases/download/${TAG}"

        MONO_PREFIX=""
        if [[ "${INPUT_DOTNET}" == "true" ]]; then
          MONO_PREFIX="mono_"
        fi

        # Export-template asset name is the same on every platform.
        TPL_ASSET="Godot_v${VERSION}-stable_${MONO_PREFIX}export_templates.tpz"

        # Per-platform variables 
        if [[ "${RUNNER_OS}" == "Linux" ]]; then
          HEADLESS_SUFFIX=""
          if [[ "${INPUT_HEADLESS}" == "true" ]]; then
            HEADLESS_SUFFIX=".headless"
          fi
          ASSET_NAME="Godot_v${VERSION}-stable_${MONO_PREFIX}linux.x86_64${HEADLESS_SUFFIX}.zip"
          GODOT_BIN_DIR="${HOME}/.local/bin"
          GODOT_INSTALL_DIR="${HOME}/.local/share/godot/install"
          GODOT_PATH="${GODOT_BIN_DIR}/godot"
          TEMPLATES_DIR="${HOME}/.local/share/godot/export_templates/${VERSION}.stable"

        elif [[ "${RUNNER_OS}" == "macOS" ]]; then
          ASSET_NAME="Godot_v${VERSION}-stable_${MONO_PREFIX}macos.universal.zip"
          GODOT_BIN_DIR="${HOME}/.local/bin"
          GODOT_INSTALL_DIR="${HOME}/.local/share/godot/install"
          GODOT_PATH="${GODOT_BIN_DIR}/godot"
          TEMPLATES_DIR="${HOME}/Library/Application Support/Godot/export_templates/${VERSION}.stable"

        else
          echo "ERROR: unsupported runner OS: ${RUNNER_OS}" >&2
          exit 1
        fi

        # Determine cache directories based on strategy
        if [[ "${INPUT_CACHE_STRATEGY}" == "github" ]]; then
          EDITOR_CACHE_DIR="/tmp/godot-cache/editor"
          TEMPLATES_CACHE_DIR="/tmp/godot-cache/templates"
        elif [[ "${INPUT_CACHE_STRATEGY}" == "local" ]]; then
          CACHE_BASE="${INPUT_LOCAL_CACHE_DIR}"
          HEADLESS_KEY=""
          if [[ "${INPUT_HEADLESS}" == "true" ]]; then
            HEADLESS_KEY="-headless"
          fi
          DOTNET_KEY=""
          if [[ "${INPUT_DOTNET}" == "true" ]]; then
            DOTNET_KEY="-dotnet"
          fi
          
          EDITOR_CACHE_DIR="${CACHE_BASE}/godot-editor-${RUNNER_OS}-${VERSION}${DOTNET_KEY}${HEADLESS_KEY}"
          TEMPLATES_CACHE_DIR="${CACHE_BASE}/godot-templates-${RUNNER_OS}-${VERSION}${DOTNET_KEY}"
        else
          # No cache - use temp directories
          EDITOR_CACHE_DIR="/tmp/godot-download-$$-editor"
          TEMPLATES_CACHE_DIR="/tmp/godot-download-$$-templates"
        fi

        # Add binary directory to PATH for future steps
        echo "${GODOT_BIN_DIR}" >> "$GITHUB_PATH"

        # Persist for all later steps 
        {
          echo "VERSION=${VERSION}"
          echo "TAG=${TAG}"
          echo "GH_BASE=${GH_BASE}"
          echo "ASSET_NAME=${ASSET_NAME}"
          echo "TPL_ASSET=${TPL_ASSET}"
          echo "GODOT_BIN_DIR=${GODOT_BIN_DIR}"
          echo "GODOT_INSTALL_DIR=${GODOT_INSTALL_DIR}"
          echo "GODOT_PATH=${GODOT_PATH}"
          echo "TEMPLATES_DIR=${TEMPLATES_DIR}"
          echo "EDITOR_CACHE_DIR=${EDITOR_CACHE_DIR}"
          echo "TEMPLATES_CACHE_DIR=${TEMPLATES_CACHE_DIR}"
          echo "CACHE_STRATEGY=${INPUT_CACHE_STRATEGY}"
        } >> "$GITHUB_ENV"

        # Step outputs for downstream jobs 
        TPL_OUT=""
        if [[ "${INPUT_TEMPLATES}" == "true" ]]; then
          TPL_OUT="${TEMPLATES_DIR}"
        fi
        {
          echo "godot-path=${GODOT_PATH}"
          echo "templates-path=${TPL_OUT}"
        } >> "$GITHUB_OUTPUT"

        echo "=== Cache strategy : ${INPUT_CACHE_STRATEGY}"
        echo "=== Resolved asset : ${ASSET_NAME}"
        echo "=== Download URL   : ${GH_BASE}/${ASSET_NAME}"
        echo "=== Editor cache   : ${EDITOR_CACHE_DIR}"
        echo "=== Templates cache: ${TEMPLATES_CACHE_DIR}"

    - uses: actions/cache@v4
      id: cache-editor-github
      if: inputs.cache-strategy == 'github'
      with:
        path: /tmp/godot-cache/editor
        key: godot-editor-${{ runner.os }}-${{ inputs.version }}-dotnet-${{ inputs.dotnet }}-headless-${{ inputs.headless }}

    - uses: actions/cache@v4
      id: cache-templates-github
      if: inputs.install-export-templates == 'true' && inputs.cache-strategy == 'github'
      with:
        path: /tmp/godot-cache/templates
        key: godot-templates-${{ runner.os }}-${{ inputs.version }}-dotnet-${{ inputs.dotnet }}

    - name: Check local cache for Godot editor
      id: cache-editor-local
      if: inputs.cache-strategy == 'local'
      shell: bash
      run: |
        if [[ -f "${EDITOR_CACHE_DIR}/${ASSET_NAME}" ]]; then
          echo "cache-hit=true" >> $GITHUB_OUTPUT
          echo ">>>> Found cached editor: ${EDITOR_CACHE_DIR}/${ASSET_NAME}"
        else
          echo "cache-hit=fales" >> $GITHUB_OUTPUT
          echo ">>>> No cahced found."
        fi

    - name: Check local cache for export templates
      id: cache-templates-local
      if: inputs.install-export-templates == 'true' && inputs.cache-strategy == 'local'
      shell: bash
      run: |
        if [[ -f "${TEMPLATES_CACHE_DIR}/${TPL_ASSET}" ]]; then
          echo "cache-hit=true" >> "$GITHUB_OUTPUT"
          echo ">>>> Found cached templates: ${TEMPLATES_CACHE_DIR}/${TPL_ASSET}"
        else
          echo "cache-hit=false" >> "$GITHUB_OUTPUT"
          echo ">>>> No cached templates found"
        fi

    - name: Download Godot editor
      shell: bash
      if: |
        (inputs.cache-strategy == 'github' && steps.cache-editor-github.outputs.cache-hit != 'true') ||
        (inputs.cache-strategy == 'local' && steps.cache-editor-local.outputs.cache-hit != 'true') ||
        inputs.cache-strategy == 'none'
      run: |
        set -euo pipefail
        mkdir -p "${EDITOR_CACHE_DIR}"
        echo "Downloading ${GH_BASE}/${ASSET_NAME} …"
        curl -sL -o "${EDITOR_CACHE_DIR}/${ASSET_NAME}" "${GH_BASE}/${ASSET_NAME}"
        echo "Download complete: $(du -h "${EDITOR_CACHE_DIR}/${ASSET_NAME}" | cut -f1)"
        if [[ "${CACHE_STRATEGY}" == "local" ]]; then
          echo "Cached to: ${EDITOR_CACHE_DIR}/${ASSET_NAME}"
        fi

    - name: Install Godot (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        set -euo pipefail
        mkdir -p /tmp/godot-install
        unzip -o "${EDITOR_CACHE_DIR}/${ASSET_NAME}" -d /tmp/godot-install

        # Move contents to install dir
        rm -rf "${GODOT_INSTALL_DIR}"
        mkdir -p "${GODOT_INSTALL_DIR}"
        # We use dotglob if set, but simple * usually works only for non-hidden.
        # To be safe, just move valid items.
        mv -f /tmp/godot-install/* "${GODOT_INSTALL_DIR}/"

        # Find binary (depth 2 allows for nested folder in zip)
        BINARY=$(find "${GODOT_INSTALL_DIR}" -maxdepth 2 -type f -executable | head -1)
        if [[ -z "${BINARY}" ]]; then
          echo "ERROR: no executable found in ${GODOT_INSTALL_DIR}" >&2
          find "${GODOT_INSTALL_DIR}"
          exit 1
        fi

        mkdir -p "${GODOT_BIN_DIR}"
        ln -sf "${BINARY}" "${GODOT_PATH}"
        chmod +x "${BINARY}"
        
        echo "Installed: ${GODOT_PATH} -> ${BINARY}"

    - name: Install Godot (macOS)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        set -euo pipefail
        mkdir -p /tmp/godot-install
        unzip -o "${EDITOR_CACHE_DIR}/${ASSET_NAME}" -d /tmp/godot-install
        # Move app bundle to install dir
        rm -rf "${GODOT_INSTALL_DIR}"
        mkdir -p "${GODOT_INSTALL_DIR}"
        if [[ -d "/tmp/godot-install/Godot.app" ]]; then
            mv -f "/tmp/godot-install/Godot.app" "${GODOT_INSTALL_DIR}/"
        else
            echo "ERROR: Godot.app not found in extracted files"
            ls -R /tmp/godot-install
            exit 1
        fi

        APP_BIN="${GODOT_INSTALL_DIR}/Godot.app/Contents/MacOS/Godot"
        if [[ ! -f "${APP_BIN}" ]]; then
           echo "ERROR: Binary not found at ${APP_BIN}"
           exit 1
        fi

        mkdir -p "${GODOT_BIN_DIR}"
        ln -sf "${APP_BIN}" "${GODOT_PATH}"
        chmod +x "${APP_BIN}"

        xattr -d com.apple.quarantine "${GODOT_INSTALL_DIR}/Godot.app" 2>/dev/null || true
        echo "Installed: ${GODOT_PATH} -> ${APP_BIN}"

    - name: Download export templates
      shell: bash
      if: >-
        inputs.install-export-templates == 'true' && (
          (inputs.cache-strategy == 'github' && steps.cache-templates-github.outputs.cache-hit != 'true') ||
          (inputs.cache-strategy == 'local' && steps.cache-templates-local.outputs.cache-hit != 'true') ||
          inputs.cache-strategy == 'none'
        )
      run: |
        set -euo pipefail
        mkdir -p "${TEMPLATES_CACHE_DIR}"
        echo "Downloading ${GH_BASE}/${TPL_ASSET} …"
        curl -sL -o "${TEMPLATES_CACHE_DIR}/${TPL_ASSET}" "${GH_BASE}/${TPL_ASSET}"
        echo "Download complete: $(du -h "${TEMPLATES_CACHE_DIR}/${TPL_ASSET}" | cut -f1)"
        if [[ "${CACHE_STRATEGY}" == "local" ]]; then
          echo "Cached to: ${TEMPLATES_CACHE_DIR}/${TPL_ASSET}"
        fi

    - name: Install export templates
      shell: bash
      if: inputs.install-export-templates == 'true'
      run: |
        set -euo pipefail
        mkdir -p "${TEMPLATES_DIR}"

        unzip -o "/tmp/godot-cache/templates/${TPL_ASSET}" -d /tmp/godot-templates-extract

        if [[ -d /tmp/godot-templates-extract/templates ]]; then
          cp -r /tmp/godot-templates-extract/templates/* "${TEMPLATES_DIR}/"
        else
          cp -r /tmp/godot-templates-extract/* "${TEMPLATES_DIR}/"
        fi

        echo "Export templates installed to: ${TEMPLATES_DIR}"
        echo "Contents:"
        ls -la "${TEMPLATES_DIR}"

    - name: Verify Godot installation
      shell: bash
      env:
        INPUT_TEMPLATES: ${{ inputs.install-export-templates }}
      run: |
        set -euo pipefail
        echo "=== Godot binary ==="
        ls -la "${GODOT_PATH}"

        echo ""
        echo "=== Version check ==="
        "${GODOT_PATH}" --headless --version

        if [[ "${INPUT_TEMPLATES}" == "true" ]]; then
          echo ""
          echo "=== Export templates ==="
          ls "${TEMPLATES_DIR}"
        fi
